### ISSUE TITLE
getting "failed to build bootstrap manifests" since v0.2.5

### ISSUE THREAD

**Issue by roi-codefresh** [argoproj-labs/argocd-autopilot#106]
since the [ref/sha/tag](https://github.com/argoproj-labs/argocd-autopilot/pull/98) change we are getting this error when running the `repo bootstrap` command:
```
FATAL failed to build bootstrap manifests: accumulating resources: accumulation err='accumulating resources from 'github.com/argoproj-labs/argocd-autopilot/manifests?tag=v0.2.5': evalsymlink failure on '/auto-pilot518561277/github.com/argoproj-labs/argocd-autopilot/manifests?tag=v0.2.5' : lstat /auto-pilot518561277/github.com: no such file or directory': evalsymlink failure on '/private/var/folders/s7/ydmj1nh917ncbk9y1mhn2dfm0000gn/T/kustomize-480526136/manifests?tag=v0.2.5' : lstat /private/var/folders/s7/ydmj1nh917ncbk9y1mhn2dfm0000gn/T/kustomize-480526136/manifests?tag=v0.2.5: no such file or directory
```

Currently I am able to get passed it by providing the `--app` flag with the correct kustomize URL, like so:
`argocd-autopilot repo bootstrap --app "github.com/argoproj-labs/argocd-autopilot/manifests?ref=v0.2.5"`

**Comment by noam-codefresh** [comment]
damn. The bootstrap manifest URL is being used directly by Kustomize, and not getting parsed by us. So it should remain with `?ref` param.
But when running `app create dir_app --app github.com/owner/name/path?tag=v0.1.2`, we *do* parse this URL for the type inference bit. And if the type ends up being Kustomize, we later just use it as the `Kustomization.yaml` source.
What a pain.

**Comment by roi-codefresh** [comment]
yep 😄
