### ISSUE TITLE
Add support for bitbucket for repo bootstrap

### ISSUE THREAD

**Issue by vainkop** [argoproj-labs/argocd-autopilot#205]
Please add support for bitbucket for repo bootstrap & provide documentation.

I see this issue is open https://github.com/argoproj-labs/argocd-autopilot/issues/7

But PR https://github.com/argoproj-labs/argocd-autopilot/pull/172 is closed so not sure if bitbucket support is there but undocumented or still missing?

Thanks

**Comment by vainkop** [comment]
Figured out how to work with bitbucket & sharing
1) create app password [https://bitbucket.org/account/settings/app-passwords](https://bitbucket.org/account/settings/app-passwords/) & use it with `export GIT_TOKEN=xxxx`
2) `export GIT_REPO="https://bitbucket.org/user/repo.git"`
3) `argocd-autopilot repo bootstrap`

**Comment by Lp-Francois** [comment]
Hello 👋 

It seems like it is not working anymore:

```
$ argocd-autopilot repo bootstrap

INFO cloning repo: https://bitbucket.org/orga/repo.git 
WARNING --provider not specified, assuming provider from url: bitbucket.org 
FATAL git provider 'bitbucket.org' not supported   
```

I guess we need to wait for official support then.

**Comment by mtrin** [comment]
@Lp-Francois 

force the github flag (it worked to me)

`argocd-autopilot repo bootstrap --provider github`
