### ISSUE TITLE
Cannot bootstrap on windows

### ISSUE THREAD

**Issue by zacharyrgonzales** [argoproj-labs/argocd-autopilot#221]
Git is using linux filepath separators which isn't accounting for windows filepath separators during the bootstrap process. 

https://cloud-native.slack.com/archives/C0207C47D0X/p1641306239049200.

**Comment by dewolfs** [comment]
Hi, I encountered the same issue today.  Changed "\" into "/" in the file: ./bootstrap/argo-cd.yaml

```
...
  source:
    path: bootstrap/argo-cd
...

```
