### ISSUE TITLE
Adding two applications with the same ns causes sync ping-pong

### ISSUE THREAD

**Issue by noam-codefresh** [argoproj-labs/argocd-autopilot#23]
When both applications create a `overlayz/<project>/namespace.yaml` file that tries to create the same namespace, Argo-CD adds different labels to the ns in each app, and it results in each application syncing over the changes from the other one.

**Comment by noam-codefresh** [comment]
I think we should have a central location where all of our `namespace` resource yamls are located. The app referencing this directory should not have any finalizers set (or at least - the namespaces themselves should be marked to not delete themselves on app deletion).

**Comment by roi-codefresh** [comment]
@noam-codefresh yeah, something like a `namespaces` application so it would have overlays for different clusters.
