### ISSUE TITLE
Adding cluster requires argocd cli login

### ISSUE THREAD

**Issue by noam-codefresh** [argoproj-labs/argocd-autopilot#24]
Currently, when adding a remote cluster, we call Argo-CD using its cli. It requires the `~/.argocd/config` file to contain the correct data for its cli to connect to Argo-CD server.

Preferably, we will add the cluster using a GitOps approach, and commit whatever Argo-CD requires, to the repo.
Also - on the remote cluster, we might create an app that also manages the SA, RB, CRB resources.

**Comment by midestefanis** [comment]
Hello, wanting to try adding a remote cluster, I couldn't find a way to do it with autopilot. I only managed it with argocd cli -> https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_cluster_add/

Seeing this closed issue, I understand that they solved this? I haven't found it in the documentation.
