### ISSUE TITLE
How to use a specific path in Gitlab

### ISSUE THREAD

**Issue by midestefanis** [argoproj-labs/argocd-autopilot#259]
With **argo-cd** cli there is the **--path** option but with autopilot I don't know how to achieve it in Gitlab

**Comment by roi-codefresh** [comment]
Hey @midestefanis, you can use the `--app` aka the "app specifier" to tell autopilot which path to use in the generated application.

You can read about it here: https://argocd-autopilot.readthedocs.io/en/stable/App-Specifier/#structure

Example: `--app https://gitlab.com/org/repo.git/path/to/kustomize-app`

**Comment by midestefanis** [comment]
@roi-codefresh Thank you very much. I had tried it that way but the server threw me 'unhautorized' and it was because I had misconfigured the access token to the repo.
