### ISSUE TITLE
Add a brew formula for autopilot

### ISSUE THREAD

**Issue by roi-codefresh** [argoproj-labs/argocd-autopilot#31]

**Comment by sestegra** [comment]
Started here #69

**Comment by sestegra** [comment]
`test` block must be defined in Homebrew formula.
Future proof test needs to be implemented with the CLI output.

Could I use as is the current default CLI output?

For instance, `argocd` formula is implementing the following.
``` ruby
test do
  assert_match "argocd controls a Argo CD server",
    shell_output("#{bin}/argocd --help")

  assert_match "argocd-util has internal utility tools used by Argo CD",
    shell_output("#{bin}/argocd-util --help")

  # Providing argocd with an empty config file returns the contexts table header
  touch testpath/"argocd-config"
  assert_match "CURRENT  NAME  SERVER\n",
    shell_output("#{bin}/argocd context --config ./argocd-config")
end
```
See https://github.com/Homebrew/homebrew-core/blob/40de9472bc82866b7220b821fa93c772a2270aef/Formula/argocd.rb#L31

**Comment by roi-codefresh** [comment]
> `test` block must be defined in Homebrew formula.
> Future proof test needs to be implemented with the CLI output.
> 
> Could I use as is the current default CLI output?
> 
> For instance, `argocd` formula is implementing the following.
> 
> ```ruby
> test do
>   assert_match "argocd controls a Argo CD server",
>     shell_output("#{bin}/argocd --help")
> 
>   assert_match "argocd-util has internal utility tools used by Argo CD",
>     shell_output("#{bin}/argocd-util --help")
> 
>   # Providing argocd with an empty config file returns the contexts table header
>   touch testpath/"argocd-config"
>   assert_match "CURRENT  NAME  SERVER\n",
>     shell_output("#{bin}/argocd context --config ./argocd-config")
> end
> ```
> 
> See https://github.com/Homebrew/homebrew-core/blob/40de9472bc82866b7220b821fa93c772a2270aef/Formula/argocd.rb#L31

Can we check that the version command is functioning?

**Comment by sestegra** [comment]
See `argocd-autopilot version` test
``` ruby
test do
  assert_match "#{version}",
    shell_output("#{bin}/argocd-autopilot version")
end
```

**Comment by roi-codefresh** [comment]
LGTM
@noam-codefresh ?

**Comment by roi-codefresh** [comment]
Thanks @sestegra! Once we are able to install with brew, would you like to add some instructions to the docs on how to do it?

**Comment by sestegra** [comment]
@roi-codefresh The issue isn't closed yet.
As soon as a new version is released, I will submit the formula to [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core)

**Comment by roi-codefresh** [comment]
@sestegra just created release v0.1.9 which includes your changes

**Comment by sestegra** [comment]
PR submitted to homebrew-core
https://github.com/Homebrew/homebrew-core/pull/78460

**Comment by sestegra** [comment]
@roi-codefresh macOS for ARM64 can't be built.
```
/opt/homebrew/Cellar/go/1.16.4/libexec/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
See full log from https://github.com/Homebrew/homebrew-core/pull/78460/checks?check_run_id=2716944236

**Comment by sestegra** [comment]
My guess is because of following line in `hack/build.sh`
```
-extldflags '-static' \
```

**Comment by roi-codefresh** [comment]
Hey @sestegra, I've just merged a PR to remove our dependency on `packr`. Guessing you need a new release that includes this?

**Comment by sestegra** [comment]
Hey @roi-codefresh, in fact, I need a new release with your update.

**Comment by roi-codefresh** [comment]
@sestegra v0.1.10 is now out :)

**Comment by sestegra** [comment]
@roi-codefresh Great, I've updated the Homebrew formula. We need to wait for homebrew-core's maintainer to approve the PR.

**Comment by sestegra** [comment]
✅  Done

Formula and bottles available on macOS: [homebrew-core/Formula/argocd-autopilot.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/argocd-autopilot.rb)
Formula and bottle available on Linux: [linuxbrew-core/Formula/argocd-autopilot.rb](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/argocd-autopilot.rb)

**Comment by roi-codefresh** [comment]
Amazing!
Thank you very much @sestegra 🥇
