### ISSUE TITLE
Add an `app delete` command

### ISSUE THREAD

**Issue by noam-codefresh** [argoproj-labs/argocd-autopilot#32]
syntax: `argocd-autopilot app delete <app_name> --project <project_name>`

Will delete the `overlay` folder. If there are no more overlays for this app, will delete the whole app folder (including the `base`)

**Comment by noam-codefresh** [comment]
Do we want to add a flag (`--global`?) that immediately deletes the entire app folder (and causes it to be deleted from all projects)?

**Comment by roi-codefresh** [comment]
SGTM
