### ISSUE TITLE
[Question] How does argocd-autopilot apply the root.yaml manifest?

### ISSUE THREAD

**Issue by jserpapinto** [argoproj-labs/argocd-autopilot#413]
Hey there,

I've been using `argocd-autopilot`, but I'm trying to reproduce it's steps manually so that I can understand them better in case something happens.

I notice that the `argocd.yaml` is applied after all the other manifests are applied. I reckon that it may be needed to do it this way so that we can track the initial deployment in argocd as well.

The initial deployment is applied in this lines: https://github.com/argoproj-labs/argocd-autopilot/blob/main/cmd/commands/repo.go#L246-L250

And then the argocd manifest is applied here: https://github.com/argoproj-labs/argocd-autopilot/blob/main/cmd/commands/repo.go#L282-L286

(tell me if I'm wrong)

But I'm not getting how does `autopilot` applies the `root.yaml` manifest.
I can't find anywhere that `manifests.rootApp` is applied.

Could any of you enlighten me plz?

**Comment by roi-codefresh** [comment]
Hey @jserpapinto, you almost got that right. But in here https://github.com/argoproj-labs/argocd-autopilot/blob/main/cmd/commands/repo.go#L282-L286 we are actually applying the `autopilot-bootstrap` application.
This application is not committed to the repo and only lives inside the cluster. It looks at `/bootstrap` path of the repo and deploys the rest of the applications (including the root app).

So I guess you could say that `autopilot-bootstrap` is the **non-gitops** root application.
