### ISSUE TITLE
How to make autopilot use a specific version of argocd?

### ISSUE THREAD

**Issue by jeffjose** [argoproj-labs/argocd-autopilot#453]
Is there a way to make argocd-autopilot to install a specific version of argocd? At the time of writing, the stable release of argocd is `v2.6.7`, which is what argocd-autopilot install. I'd like to install `v2.7.0-rc1`, which just came out.

**Comment by polinchw** [comment]
I think you can do this by using Kustomize patches on the argocd folder within the root folder of your auto-pilot repo.

**Comment by dusatvoj** [comment]
@polinchw, do you know how?

**Comment by MMartyn** [comment]
Did you end up figuring this out?

**Comment by dusatvoj** [comment]
@MMartyn I gave up using autopilot and switched to argo-cd helm chart with app of apps pattern.

https://artifacthub.io/packages/helm/argo/argo-cd
https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/#app-of-apps-pattern
