### ISSUE TITLE
All deployed applications getting deleted

### ISSUE THREAD

**Issue by lgkgh** [argoproj-labs/argocd-autopilot#494]
Hi,

I am stuck with a problem and would really appreciate some help and guidance.

We have Argo CD deployed on DigitalOcean DOKS (version 1.26.5-do.0) through Argo CD Autopilot. The Argo CD deployment was functioning as expected and applications could be deployed and updated.

Two weeks ago we had an incident where all the applications were deleted from Argo CD, across several clusters. We have been trying to reproduce the problem and we were able to get a similar result compared to what we saw during our production incident.

Steps to reproduce the application delete:

1. Use Argo CD Autopilot to bootstrap a new cluster
2. Enable the Argo CD Vault Plugin (using the [InitContainer and configuration via sidecar](https://argocd-vault-plugin.readthedocs.io/en/stable/installation/) installation)
3. At this stage the behaviour is as expected.
4. To trigger the application delete, a change can be applied to the argo-cd `kustomization.yaml`. For example to add `test-secret.yaml` as a resource, as shown in the example below.
5. The result is that all applications are deleted, except for autopilot-bootstrap.

I am trying to understand why all the applications are being deleted and what I can do to prevent this from happening. The only way that I have been able to reproduce this behaviour was to apply changes to some applications, argo-cd is a good example, only after the AVP has been deployed. Important to note that AVP is functioning as expected.

To recover from the application delete, I can run `argocd-autopilot repo bootstrap --recover` and do a hard refresh on autopilot-bootstrap. This will then redeploy all the applications, root, cluster resources and argo-cd.

Example: Adding `test-secret.yaml` in `argocd-autopilot/bootstrap/argo-cd/kustomization.yaml` below will trigger a delete of all deployed applications on Argo CD, except for autopilot-bootstrap (delete is triggered only after AVP has been deployed).

```
apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - |
    repository.credentials=- passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://github.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
  name: argocd-cm
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=v0.4.15
- cmp-plugin.yaml
- test-secret.yaml

patchesStrategicMerge:
- argocd-repo-server-patch.yaml
```
Log output from argocd-application-controller showing the application delete:
```
time="2023-07-19T11:49:31Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=argocd/autopilot-bootstrap
time="2023-07-19T11:49:31Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc/, namespace: argocd)" application=argocd/autopilot-bootstrap
time="2023-07-19T11:49:31Z" level=info msg="Deleting resources" application=argocd/root
time="2023-07-19T11:49:31Z" level=info msg="Adding resource result, status: 'Pruned', phase: 'Succeeded', message: 'pruned'" application=argocd/autopilot-bootstrap kind=Application name=root namespace=argocd phase=Sync syncId=00021-EqrWW
time="2023-07-19T11:49:31Z" level=info msg="Adding resource result, status: 'Pruned', phase: 'Succeeded', message: 'pruned'" application=argocd/autopilot-bootstrap kind=ApplicationSet name=cluster-resources namespace=argocd phase=Sync syncId=00021-EqrWW
time="2023-07-19T11:49:31Z" level=info msg="Adding resource result, status: 'Pruned', phase: 'Succeeded', message: 'pruned'" application=argocd/autopilot-bootstrap kind=Application name=argo-cd namespace=argocd phase=Sync syncId=00021-EqrWW
time="2023-07-19T11:49:31Z" level=info msg="Updating operation state. phase: Running -> Succeeded, message: 'one or more tasks are running' -> 'successfully synced (all tasks run)'" application=argocd/autopilot-bootstrap syncId=00021-EqrWW
time="2023-07-19T11:49:31Z" level=info msg="sync/terminate complete" application=argocd/autopilot-bootstrap duration=63.749006ms syncId=00021-EqrWW
time="2023-07-19T11:49:31Z" level=info msg="Deleting application's resources with Foreground propagation policy" application=argocd/root
time="2023-07-19T11:49:31Z" level=info msg="getRepoObjs stats" application=argocd/autopilot-bootstrap build_options_ms=0 helm_ms=1 plugins_ms=0 repo_ms=0 time_ms=27 unmarshal_ms=26 version_ms=0
time="2023-07-19T11:49:31Z" level=info msg="Skipping auto-sync: another operation is in progress" application=argocd/autopilot-bootstrap
time="2023-07-19T11:49:31Z" level=info msg="Updated health status: Healthy -> Progressing" application=autopilot-bootstrap dest-namespace=argocd dest-server="https://kubernetes.default.svc/" reason=ResourceUpdated type=Normal
time="2023-07-19T11:49:31Z" level=info msg="updated 'argocd/autopilot-bootstrap' operation (phase: Succeeded)"
time="2023-07-19T11:49:31Z" level=info msg="Sync operation to 0c320cb156fec4aa043b3580aa2a065e789a2735 succeeded" application=autopilot-bootstrap dest-namespace=argocd dest-server="https://kubernetes.default.svc/" reason=OperationCompleted type=Normal
time="2023-07-19T11:49:31Z" level=info msg="Unable to delete application resources: Application.argoproj.io \"root\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"foregroundDeletion\"}" application=root dest-namespace=argocd dest-server="https://kubernetes.default.svc/" reason=StatusRefreshed type=Warning
time="2023-07-19T11:49:31Z" level=info msg="Deleting resources" application=argocd/root
time="2023-07-19T11:49:31Z" level=info msg="Deleting application's resources with Foreground propagation policy" application=argocd/root
time="2023-07-19T11:49:31Z" level=info msg="Update successful" application=argocd/autopilot-bootstrap
time="2023-07-19T11:49:31Z" level=info msg="Reconciliation completed" application=argocd/autopilot-bootstrap dedup_ms=0 dest-name= dest-namespace=argocd dest-server="https://kubernetes.default.svc/" diff_ms=7 fields.level=1 git_ms=28 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=66
time="2023-07-19T11:49:31Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=argocd/autopilot-bootstrap
time="2023-07-19T11:49:31Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc/, namespace: argocd)" application=argocd/autopilot-bootstrap
time="2023-07-19T11:49:31Z" level=info msg="Successfully deleted 0 resources" application=argocd/root
time="2023-07-19T11:49:31Z" level=info msg="getRepoObjs stats" application=argocd/autopilot-bootstrap build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=18 unmarshal_ms=17 version_ms=0
time="2023-07-19T11:49:31Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd/autopilot-bootstrap
time="2023-07-19T11:49:31Z" level=info msg="Updated sync status: OutOfSync -> Synced" application=autopilot-bootstrap dest-namespace=argocd dest-server="https://kubernetes.default.svc/" reason=ResourceUpdated type=Normal
time="2023-07-19T11:49:31Z" level=info msg="Update successful" application=argocd/autopilot-bootstrap
time="2023-07-19T11:49:31Z" level=info msg="Reconciliation completed" application=argocd/autopilot-bootstrap dedup_ms=0 dest-name= dest-namespace=argocd dest-server="https://kubernetes.default.svc/" diff_ms=0 fields.level=2 git_ms=18 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=52
```

**Comment by todaywasawesome** [comment]
@lgkgh Argo CD Autopilot sets all apps up with argocd finalizers and prune enabled. This behavior means if a resource is deleted in git it will automatically be deleted. But there are two other scenarios that would also cause deletion, Argo CD it self being deleted, and a failure of resources to render.

If resources have the Argo CD finalizer set, then when Argo CD is removed there is nothing holding the finalizer condition and Kubernetes will automatically remove the resouces.

If resources fail to render, and I've seen lots of issues with kustomize rendering but dropping resources for various reasons then they will automatically be pruned. 

To prevent this from happening you'll need to modify the applicationset to not set the finalizer and not enable pruning. Then deleting applications will need to be done manually. Note you can still leave pruning and finalizers on for individual application, but disable it for the application definitions themselves. Then you only have to worry about deleting applications manually. 

Hope that helps.

**Comment by lgkgh** [comment]
Hi @todaywasawesome,

Thank you very much for the information.
