### ISSUE TITLE
app create does not work with local path (tries to infer application type by cloning)

### ISSUE THREAD

**Issue by roi-codefresh** [argoproj-labs/argocd-autopilot#87]
When trying `argocd-autopilot app create demoapp -p prod --app /tmp/test` I receive an error
```
INFO Cloning repo: '', to infer app type from path '/tmp/test'
FATAL URL field is required
```

**Comment by noam-codefresh** [comment]
Workaround:
add the `--type dir` or `--type kustomize` flag (for Directory application or Kustomize application) to the command line
