### ISSUE TITLE
Do you support azure git provider ?

### ISSUE THREAD

**Issue by vspherewithtanzu** [argoproj-labs/argocd-autopilot#94]
I am able to add repo using argocd but fails with argocd-autopilot 
FATAL authentication failed, make sure credentials are correct: GET https://dev.azure.com/<my organization>/api/v3/user: 401  []

**Comment by roi-codefresh** [comment]
Hey @vpsheretanzu, which command did you run?

**Comment by vpsheretanzu** [comment]
argocd-autopilot repo create --owner orgname --name username --host https://dev.azure.com/orgname/ --git-token $MY_PAT
INFO creating repo: orgname/username
FATAL authentication failed, make sure credentials are correct: GET https://dev.azure.com/orgname/api/v3/user: 401  []

**Comment by noam-codefresh** [comment]
Autopilot currently only supports GitHub repositories. We plan on supporting other git cloud providers in the future.

**Comment by rumstead** [comment]
I would be happy to implement this. Are suggestions on the impl other than adding a new provider called azure that implements the `provider` interface?

**Comment by roi-codefresh** [comment]
Hey @rumstead we would be happy to accept contributions. It should be relatively easy to add support for another provider. We recently implemented support for gitlab, you can take a look here #209.

**Comment by rumstead** [comment]
Awesome sign me up

**Comment by roi-codefresh** [comment]
released with v0.2.28
